/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PropFirmsRouteImport } from './routes/prop-firms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmsRoute = PropFirmsRouteImport.update({
  id: '/prop-firms',
  path: '/prop-firms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/prop-firms': typeof PropFirmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/prop-firms': typeof PropFirmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/prop-firms': typeof PropFirmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/journal' | '/news' | '/profile' | '/prop-firms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/journal' | '/news' | '/profile' | '/prop-firms'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/journal'
    | '/news'
    | '/profile'
    | '/prop-firms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  PropFirmsRoute: typeof PropFirmsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firms': {
      id: '/prop-firms'
      path: '/prop-firms'
      fullPath: '/prop-firms'
      preLoaderRoute: typeof PropFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  PropFirmsRoute: PropFirmsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
